output_root: '../'
pytorch_data_dir: '/home/hossein/data/segmentation'
experiment_name: "cocostuff"
res: 320
batch_size: 8
num_workers: 24
run_picie: True
run_crf: True
run_prediction: True
dark_mode: True
use_ddp: False
cuda_n: "1"

model_paths:
  - "../saved_models/cocostuff27_vit_base_5.ckpt"
  #- "../saved_models/cityscapes_vit_base_1.ckpt"
  #- "../saved_models/potsdam_test.ckpt"

hydra:
  run:
    dir: "."
  output_subdir: ~
  #job_logging: "disabled"
  #hydra_logging: "disabled"
